[package]
name = "fmt_int"
version = "0.2.1"
edition = "2024"
rust-version = "1.98.0"

[[bench]]
name = "fmt_binary"
path = "benches/fmt_binary.rs"
harness = false

[[bench]]
name = "fmt_octal"
path = "benches/fmt_octal.rs"
harness = false

[[bench]]
name = "fmt_decimal"
path = "benches/fmt_decimal.rs"
harness = false

[[bench]]
name = "fmt_hex"
path = "benches/fmt_hex.rs"
harness = false

[[bench]]
name = "str_concat"
path = "benches/str_concat.rs"
harness = false

[dev-dependencies]
criterion = "0.8.2"
numtoa = "1.0.1"
